// Code generated by MockGen. DO NOT EDIT.
// Source: filesystem/file_walker.go

// Package filesystem is a generated GoMock package.
package filesystem

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockFileWalker is a mock of FileWalker interface
type MockFileWalker struct {
	ctrl     *gomock.Controller
	recorder *MockFileWalkerMockRecorder
}

// MockFileWalkerMockRecorder is the mock recorder for MockFileWalker
type MockFileWalkerMockRecorder struct {
	mock *MockFileWalker
}

// NewMockFileWalker creates a new mock instance
func NewMockFileWalker(ctrl *gomock.Controller) *MockFileWalker {
	mock := &MockFileWalker{ctrl: ctrl}
	mock.recorder = &MockFileWalkerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockFileWalker) EXPECT() *MockFileWalkerMockRecorder {
	return m.recorder
}

// Walk mocks base method
func (m *MockFileWalker) Walk() ([]WalkedFile, error) {
	ret := m.ctrl.Call(m, "Walk")
	ret0, _ := ret[0].([]WalkedFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Walk indicates an expected call of Walk
func (mr *MockFileWalkerMockRecorder) Walk() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Walk", reflect.TypeOf((*MockFileWalker)(nil).Walk))
}
