#!/usr/bin/env bash

set -e -u -o pipefail

OUTPUT=$PWD/scantron-binary

export GOPATH=$PWD/go
export PATH=$GOPATH/bin:$PATH

pushd "${GOPATH}/src/github.com/pivotal-cf/scantron" > /dev/null
  go get -u github.com/golang/dep/cmd/dep
  dep ensure -v

  ./scripts/test
popd > /dev/null

mv "${GOPATH}/src/github.com/pivotal-cf/scantron/scantron" "${OUTPUT}"
