#!/usr/bin/env bash

set -e -u

# set tag name
date +%Y-%m-%d > release-params/tag-name

# set tag commit
git --git-dir="scantron/.git" rev-parse HEAD > ../release-params/commit-sha

# set release name
date "+%b %e, %Y" > release-params/release-name
