#!/bin/bash

set -eux

go get github.com/rakyll/statik

rm data/proc_scan/* || true
rm scantron || true
rm -rf statik*

statik -src=data -p statik
GOOS=linux GOARCH=amd64 go build -o data/proc_scan/proc_scan_linux ./cmd/proc_scan
GOOS=windows GOARCH=amd64 go build -o data/proc_scan/proc_scan_windows ./cmd/proc_scan

statik -src=data -p statik -f # overwrite statik.go to include the two proc_scan binaries in addition to the tls-parameters.csv
GOOS=linux GOARCH=amd64 go build -o scantron ./cmd/scantron
