#!/bin/bash

set -eux

go get -u github.com/jteeuwen/go-bindata/...

rm data/proc_scan || true # file grows on each run
rm proc_scan.go || true

GOOS=linux GOARCH=amd64 go build -o data/proc_scan ./cmd/proc_scan
$GOPATH/bin/go-bindata -o proc_scan.go -pkg scantron data

go build -o scantron ./cmd/scantron
