#!/usr/bin/env bash

set -eu

go get github.com/onsi/ginkgo/ginkgo
go get github.com/onsi/gomega/...

my_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
root_dir="$( cd "${my_dir}/.." && pwd )"

pushd "${root_dir}" > /dev/null
  ./scripts/build

  $GOPATH/bin/ginkgo \
    -r \
    -p \
    -race \
    -failOnPending \
    -randomizeAllSpecs \
    -randomizeSuites \
    "$@"

popd > /dev/null
