#!/usr/bin/env bash

set -e -u -o pipefail

export GOPATH=$PWD/go
export PATH=$GOPATH/bin:$PATH

pushd $GOPATH/src/github.com/pivotal-cf/scantron
  glide install

  ln -s $PWD/vendor /tmp/src
  GOPATH=/tmp go install github.com/onsi/ginkgo/ginkgo

  ginkgo -r -p -race "$@"
popd
