#!/usr/bin/env bash

set -e -u -o pipefail

OUTPUT=$PWD/scantron-binary

export GOPATH=$PWD/go
export PATH=$GOPATH/bin:$PATH

go get -u github.com/golang/dep/...

pushd $GOPATH/src/github.com/pivotal-cf/scantron
  dep ensure

  go install ./vendor/github.com/onsi/ginkgo/ginkgo

  ./build.sh

  ginkgo -r -p -race "$@"
popd

mv $GOPATH/src/github.com/pivotal-cf/scantron/scantron $OUTPUT
